# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-14 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190708_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_active',
            field=models.BooleanField(default=False),
        ),
    ]
