# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-25 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserOpenid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('open_id', models.CharField(db_index=True, max_length=50, verbose_name='open_id')),
            ],
            options={
                'verbose_name': 'QQ登陆用户数据',
                'db_table': 'tb_auth_qq',
                'verbose_name_plural': 'QQ登陆用户数据',
            },
        ),
    ]
